databases:
  - name: company_db
    databaseName: company_db
    user: appy

services:
  - type: web
    name: company-DB
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: company_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false